// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pRryzyBTrb4e_yqU_LpM99wH-zxP_5s',
    appId: '1:187252915740:web:ae8391eb31a927e297a9d9',
    messagingSenderId: '187252915740',
    projectId: 'cloud-database-equitysoft',
    authDomain: 'cloud-database-equitysoft.firebaseapp.com',
    databaseURL: 'https://cloud-database-equitysoft-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-database-equitysoft.appspot.com',
    measurementId: 'G-0YXP1D01VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCMj_R_DtHIxW7VYQ_epQQUb9DxrJBRQ',
    appId: '1:187252915740:android:e46b887578d11d8897a9d9',
    messagingSenderId: '187252915740',
    projectId: 'cloud-database-equitysoft',
    databaseURL: 'https://cloud-database-equitysoft-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-database-equitysoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXzAPoMR1kfOTTOd3qoyfvMuhefuJFNk',
    appId: '1:187252915740:ios:4a020dd77efe2f0697a9d9',
    messagingSenderId: '187252915740',
    projectId: 'cloud-database-equitysoft',
    databaseURL: 'https://cloud-database-equitysoft-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-database-equitysoft.appspot.com',
    iosBundleId: 'com.example.equitysoftAddUpdateDeleteViewDataLocalStorageDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRXzAPoMR1kfOTTOd3qoyfvMuhefuJFNk',
    appId: '1:187252915740:ios:e1a53f3b2f01f23d97a9d9',
    messagingSenderId: '187252915740',
    projectId: 'cloud-database-equitysoft',
    databaseURL: 'https://cloud-database-equitysoft-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-database-equitysoft.appspot.com',
    iosBundleId: 'com.example.equitysoftAddUpdateDeleteViewDataLocalStorageDatabase.RunnerTests',
  );
}
